languageCode = "en"
languageName = "English"
weight = 1
title = "blogger"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "0x6c79"
headline = "I'm only human"
bio = "A little bit about you"
image = "00008.png"
