[[main]]
name = "Blog"
pageRef = "posts"
weight = 1

[[main]]
name = "Parent"
weight = 5

[[main]]
name = "example sub-menu 1"
parent = "Parent"
pageRef = "posts"
weight = 4

[[main]]
name = "Categories"
pageRef = "categories"
weight = 2

[[main]]
name = "Tags"
pageRef = "tags"
weight = 6

[[main]]
name = "Blog"
pageRef = "posts"
weight = 1

[[main]]
name = "Parent"
weight = 5

[[main]]
name = "example sub-menu 2"
parent = "Parent"
pageRef = "posts"
weight = 3

[[main]]
name = "Categories"
pageRef = "categories"
weight = 2

[[main]]
name = "Tags"
pageRef = "tags"
weight = 6

[[subnavigation]]
name = "An interesting topic"
pageRef = "tags/interesting-topic"
weight = 10

[[subnavigation]]
name = "My Awesome Category"
pre = "github"
pageRef = "categories/awesome"
weight = 20

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20
