colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
disableImageOptimization = false
disableTextInHeader = false
defaultBackgroundImage = "sr26a2d9f2fccaws3.gif"
defaultFeaturedImage = "false"
highlightCurrentMenuArea = ""
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = "5"
showMoreLink = false
showMoreLinkDest = "/posts"
cardView = false
cardViewScreenWidth = ""
layoutBackgroundBlur = true
homepageImage = "sr26a2d9f2fccaws3.gif"

[article]
showDate = true
showViews = false
showLikes = false
showDateUpdated = false
showAuthor = true
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = ""
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = ""
showReadingTime = true
showTableOfContents = true
showTaxonomies = ""
showAuthorsBadges = false
showWordCount = true
heroStyle = "background"
showRelatedContent = ""
relatedContentLimit = ""
showZenMode = true

[list]
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = true
showCards = ""
groupByYear = true
cardView = false
cardViewScreenWidth = ""
constrainItemsWidth = ""
heroStyle = "background"

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = ""
cardView = ""
heroStyle = "background"

[term]
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false
heroStyle = "background"

[firebase]

[fathomAnalytics]

[buymeacoffee]

[verification]
